import React from 'react'

export default function Ex06() {
  return (
    <div className='h-[200px] w-[500px] overflow-auto '>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga consectetur, dignissimos quae excepturi omnis dolores quam placeat dicta autem nisi modi veritatis blanditiis obcaecati repudiandae impedit ex nobis inventore. Harum.
        Voluptatem velit autem deleniti adipisci distinctio numquam labore quidem voluptas ratione tempora? Quas ea eius saepe, maiores repellat fugiat earum explicabo quae culpa natus, minus distinctio assumenda aperiam dolore quod.
        Consectetur repellendus dolores mollitia commodi architecto laudantium sint earum veniam exercitationem voluptatibus explicabo quos ea cumque odio praesentium ab rem unde, ipsum magnam maiores aspernatur deserunt eligendi molestiae impedit. Rem!
        Perferendis, autem soluta! Officia delectus optio similique libero voluptatem cumque neque, voluptates expedita in doloribus natus odio excepturi aut quod iste animi? Quisquam omnis molestiae, doloribus expedita voluptas fugiat dolorem.
        Harum placeat sed voluptates dolores libero, vel incidunt reiciendis similique molestiae laborum blanditiis quo! Quaerat aperiam laborum, hic nostrum iure consequatur necessitatibus deserunt nesciunt magni iusto distinctio in maxime veniam!
        Et nemo tempora minima dolor facere sapiente illo omnis perspiciatis? Itaque perspiciatis esse delectus facilis, iure sed ipsam vitae ratione repellat quaerat recusandae alias exercitationem sapiente doloribus deleniti saepe provident?
        Suscipit aliquid quaerat optio exercitationem? Cumque fugiat doloremque ipsum odio quae quod possimus recusandae architecto laborum blanditiis, sapiente nostrum, omnis harum officia eos animi, porro est et. Quisquam, ipsa. In.
        Impedit soluta labore eius. Eligendi repellat qui obcaecati nobis quaerat non delectus laborum molestiae a voluptatum optio voluptatem, illo cupiditate ipsa pariatur numquam odio exercitationem nesciunt, nostrum ea vero consectetur.
        Doloribus totam cupiditate dicta eligendi asperiores magnam quod veniam a adipisci repellat nesciunt ducimus omnis, accusantium iure id sunt dolore. Commodi omnis alias neque possimus, beatae rem amet perferendis aut.
        Voluptatibus sequi sit nemo distinctio beatae eaque magni amet optio harum quo molestiae velit praesentium, perferendis accusamus non quas. Ratione eum dicta, nulla quam inventore cum porro voluptates odit sed.
        Rem eius nostrum minima, quas, deleniti placeat maiores nesciunt, quae voluptatum suscipit saepe! Ex voluptate tempore numquam perspiciatis totam vitae maiores magnam porro incidunt fugiat! A quod ipsa quam quae!
        Exercitationem quo dolorem nesciunt error repellendus provident voluptas facere aut veniam quibusdam corporis, architecto ullam dolore, suscipit temporibus, eveniet officiis natus illum. Velit a veritatis ut eum explicabo minima veniam?
        Repudiandae distinctio quaerat reiciendis sit praesentium voluptatem harum at fugit tempore, error molestiae? Asperiores minus, assumenda explicabo saepe nulla sit illo molestias perspiciatis perferendis voluptates recusandae excepturi quis eligendi esse!
        Eius accusantium molestias corporis nostrum quis delectus quo vero totam, rem possimus necessitatibus dicta laudantium ea architecto debitis quas nemo consectetur voluptatem esse provident itaque dolor fugit! Blanditiis, iste temporibus.
        Accusantium fugiat officia itaque placeat dolores distinctio ullam! Modi perferendis minus esse aliquam quam quod tempore eius sequi quas blanditiis saepe quis, vitae nisi expedita est quo? Possimus, sed explicabo!
        Nam, incidunt tempore amet commodi cumque corrupti in quis dicta itaque provident eius suscipit adipisci, unde molestias cum aspernatur consectetur ad eos ratione voluptate nesciunt recusandae vitae? Ab, eum ullam.
        Officiis sequi libero odio dicta commodi voluptates delectus vitae ullam dolor praesentium nobis et dolore, adipisci at. Ut dolor repellat rerum officiis voluptatum reprehenderit optio dolorum rem! Eius, veritatis dicta?
        Aut facere, nihil pariatur iste dicta fuga alias unde libero dolores laudantium velit est fugit, voluptates deleniti? Sunt beatae velit dolore culpa, doloremque, ullam illo iusto facilis porro adipisci enim.
        Tempore quod perspiciatis rerum quasi consectetur. Odit neque, repellendus numquam ducimus quo id molestias totam illum eligendi saepe amet consequatur minima iure iste ipsum libero dolorem officia. Cum, sit laudantium.
        Nulla soluta doloremque libero maxime fugiat perspiciatis, amet quae maiores deleniti doloribus tempora facere et dicta corrupti cum, nesciunt dolorem ducimus quis dolor. Aspernatur, rerum. Sint expedita quasi nostrum modi.
        Asperiores fugiat ipsam maiores obcaecati est aspernatur deleniti, tempore praesentium libero atque aliquam voluptate nisi dolorem. At sed praesentium excepturi sunt velit tempora iusto animi tenetur eos non? Maiores, praesentium!
        Ea debitis et reiciendis nihil vitae saepe corporis maxime aspernatur eos ipsa, magni, exercitationem obcaecati qui perferendis molestias asperiores aliquid optio delectus nulla ut non tempora! Perspiciatis quibusdam id beatae?
        Minima corporis ratione totam, quidem numquam, magni quae laudantium tenetur enim culpa nobis eius quas ipsa! Ut nostrum, fuga consequatur ab minus, voluptas iusto magnam incidunt unde similique fugiat porro?
        Itaque eos eum sit ex officiis autem earum maiores temporibus, neque voluptates illum quas provident error voluptas ullam quisquam ut consequatur, veritatis animi! Nam omnis inventore harum incidunt eaque hic?
        Nemo nesciunt incidunt sunt debitis animi, illo possimus facilis totam officia. Nam saepe magnam voluptate iste unde laboriosam impedit, repudiandae facilis nobis vero pariatur inventore, quos, veniam nesciunt tempora possimus.
        Tempora, dolorum quisquam excepturi quasi delectus ex quibusdam id corrupti beatae incidunt perspiciatis sequi deserunt, quas maiores voluptatibus quis architecto obcaecati exercitationem laboriosam? Voluptas, ullam expedita commodi quisquam ad necessitatibus.
        Vitae tempora, et repellat quo voluptate ab numquam rem vero aliquam blanditiis, odio voluptatem natus vel magni voluptas corrupti eos beatae eaque assumenda illo minima fugiat est dolores. At, exercitationem.
        Omnis possimus quidem eveniet, quibusdam perspiciatis eum illum magnam. Harum eaque molestias commodi numquam velit cupiditate quidem alias quod voluptates laudantium, eius nisi. Ex ut illo sapiente possimus culpa animi!
        Molestiae explicabo, harum tempore cupiditate totam dignissimos alias magni neque voluptatibus ad maxime ducimus, perferendis consectetur inventore voluptas provident et esse, quibusdam nisi aperiam reiciendis. Deleniti illum iusto dolore obcaecati.
        Sunt doloribus magni fugit consequuntur facere mollitia accusantium dignissimos dicta eveniet totam labore repellendus blanditiis adipisci quae similique facilis aut explicabo unde ipsam corporis architecto quam ullam, debitis natus. Natus?
        A eligendi excepturi recusandae soluta laboriosam laborum aperiam iure temporibus iusto saepe ducimus tempore eius sapiente, animi perferendis vitae, delectus libero minus molestias quaerat sunt eos? Numquam delectus id quasi.
        Veritatis dolor explicabo aliquid, atque ut officiis fuga quae minima, cum cumque repudiandae consequatur cupiditate enim deserunt labore neque aperiam ex fugit quo error architecto? Inventore, deleniti! Obcaecati, dolorum ea?
        Provident deserunt numquam iure. Deleniti ab beatae dolorem eius nesciunt et eaque, rerum, magnam ipsa non quo, impedit debitis quos sit ullam. Alias pariatur saepe, cupiditate velit commodi aperiam ducimus!
        Labore quae atque assumenda consectetur exercitationem, eos molestias beatae tempore quasi. Ratione nisi quae aliquam, optio consectetur aliquid voluptatem consequatur omnis iste eos vel aperiam id culpa, ducimus minus perferendis!
        Nostrum pariatur modi id omnis. Beatae esse doloribus quod velit voluptatem officiis, nulla maxime tempora inventore minus debitis iure architecto quaerat commodi veniam eius repudiandae quas! Quos accusantium dolorem beatae.
        Hic veritatis quis consequatur, quaerat non blanditiis alias neque perspiciatis adipisci! Pariatur porro cupiditate ipsam harum temporibus perspiciatis? Eius temporibus vel eos eum recusandae possimus aspernatur, mollitia quis tempora? Animi!
        Ratione aut delectus quis quaerat porro accusantium pariatur doloremque voluptatibus nihil, deserunt voluptatem tempora quae reiciendis velit enim ipsum reprehenderit soluta perspiciatis. Quis excepturi quasi recusandae, eius totam tenetur sint!
        Doloremque non numquam quibusdam eveniet aperiam impedit repudiandae neque. Accusantium optio nostrum aliquid enim laboriosam, quis rerum quidem quas? Sequi excepturi rem illo eius repellat delectus voluptates totam autem laboriosam?
        Quidem tenetur autem ea quaerat reiciendis a, odio nulla pariatur tempora? Molestias, iusto blanditiis quos ad, autem necessitatibus pariatur quas veniam quam sint quasi. Explicabo atque fuga dolorum nobis quaerat.
        Quod voluptates reiciendis hic dolor, iure itaque facilis optio deleniti. Cumque, placeat nostrum illo tenetur repellendus explicabo dolorem nihil possimus ab animi exercitationem sint! Ipsum similique repellendus ducimus praesentium blanditiis.
        Doloremque minima expedita, eaque similique totam earum quod est culpa sit, possimus porro consequuntur nam, ipsam tempora! Doloribus, distinctio. Fuga suscipit cumque accusantium veritatis necessitatibus amet temporibus exercitationem rem unde?
        Amet excepturi dolor mollitia accusamus consequatur, eaque, totam similique a voluptates, sed laboriosam eius repellendus sequi! Nam nesciunt officia nulla, repellendus esse similique dolores. Maxime est cumque eius facilis at.
        Accusantium quos ipsum a accusamus nulla error eveniet inventore molestiae delectus culpa mollitia praesentium, earum temporibus voluptatem nihil commodi provident minus voluptatibus deleniti esse laborum? Molestiae sapiente voluptas odit recusandae.
        Voluptate architecto, nulla asperiores provident nesciunt, hic soluta, culpa dolores ipsa ratione reprehenderit minima harum nam accusamus autem distinctio reiciendis eum quos atque odit consequatur dolorum velit quasi? Nesciunt, voluptatum.
        Autem dicta explicabo consequuntur molestias assumenda quia ipsam ad aliquam qui porro eos inventore, distinctio accusantium cupiditate natus iste accusamus necessitatibus non ut quidem. Hic, sint quas. Eaque, repellat. Eveniet.
        Expedita veniam provident aliquid dignissimos reprehenderit reiciendis neque non eos, nobis itaque modi animi. Consequuntur cum, iste aut distinctio mollitia minus repudiandae expedita, provident veritatis ipsum magni consequatur aliquid eveniet?
        Earum, itaque. Blanditiis asperiores minima nam molestiae ratione commodi quaerat porro dicta saepe est, eos dolorem odio suscipit vel? Aliquid perspiciatis eveniet, facere explicabo doloremque non necessitatibus tempora ab dolore!
        Cum cumque sapiente, iusto neque sint sunt saepe? Nam voluptatibus, maxime consequatur commodi a ducimus esse modi, itaque maiores dolorem quas consequuntur soluta rem veniam placeat ullam aliquid quam explicabo.
        Sit sint dolor dignissimos, molestiae praesentium voluptatum. Illum consectetur facere totam consequuntur itaque mollitia aliquid, quibusdam assumenda eaque ea vel tempora modi possimus ipsum debitis! Nostrum voluptas illum aperiam tempora.
        Voluptates, excepturi nobis commodi nam provident est amet animi quas adipisci sed earum maxime nostrum, exercitationem maiores atque doloribus nisi magnam ratione hic rem ad consequuntur? Explicabo perferendis fugiat obcaecati.
    </div>
  )
}
